drv/stm32cube/bsp_uart.c
drv/stm32cube/inc/stm32f4xx_hal_uart.h

Some UART speeds were incorrectly set and reported.
Source:
STM32F405 reference manual
30.3.4 page 965:
USARTDIV is an unsigned fixed point number that is coded on the
USART_BRR register.
Note:
• When OVER8=0, the fractional part is coded on 4 bits and programmed by the
DIV_fraction[3:0] bits in the USART_BRR register
• When OVER8=1, the fractional part is coded on 3 bits and programmed by the
DIV_fraction[2:0] bits in the USART_BRR register, and bit
DIV_fraction[3] must be kept
cleared.

UART: fix bug in baudrate->BRR

---

common/exec.c
hydrabus/commands.c
hydrabus/commands.h
hydrabus/hydrabus.mk
hydrabus/hydrabus_mode.c
hydrabus/hydrabus_mode_jtag.c
hydrabus/hydrabus_mode_jtag.h

Software JTAG for Hydrabus.
=======================
This is a first implementation of the JTAG protocol for the HydraBus
Features : 
---------------
- Classic JTAG (TDI/TDO/TMS/TCK)
- Can be used with command line
- BusPirate-compatible OpenOCD binary mode ( _openocd_ command)
-  Can scan a JTAG bus with IDCODE and BYPASS methods ( _idcode_ and _bypass_ commands)
- Can try to find  JTAG bus on all GPIOB pins (like JTAGulator) ( _brute_ command)
TODO:
----------
- Enhance port speed
- Enhance binary mode
- Add support for TRST
- Add support for MSB/LSB when reading

software JTAG mode

---

common/common.h
common/exec.c
drv/stm32cube/bsp_rng.c
drv/stm32cube/bsp_rng.h
drv/stm32cube/stm32cube.mk
hydrabus/commands.c
hydrabus/commands.h
hydrabus/hydrabus.mk
hydrabus/hydrabus_rng.c

Support for STM32 hardware RNG
- new  *random* command returns a 32bit random number in hex

STM32 hardware RNG support

---

drv/stm32cube/bsp_rng.c
hydrabus/commands.c
hydrabus/commands.h
hydrabus/hydrabus_mode.c
hydrabus/hydrabus_rng.c

Command line now supports the *~* command to write a random byte.
Example : 
```
> uart 
Device: UART1
Speed: 9600 bps
Parity: none
Stop bits: 1
uart1> ~ ~ ~ ~ ~
WRITE: 0x3F 0x40 0x4A 0x59 0xC0 
uart1> ~:5
WRITE: 0xEC 0xEC 0xEC 0xEC 0xEC 
uart1> 
```

Addrd new token ~ to write random byte

---

hydrabus/hydrabus_sump.c

Removed interrupt vector deinit, since no interruption is handled here.
Disable TIM4 once done.

Correct SUMP deinit

---

hydrabus/commands.c
hydrabus/hydrabus_mode.c

This patch adds the possibility to write strings in the command line that will be converted to their ASCII counterpart before being sent on each protocol : 
```
> uart 
Device: UART1
Speed: 9600 bps
Parity: none
Stop bits: 1
uart1> "Hello world"
WRITE: 0x48 0x65 0x6C 0x6C 0x6F 0x20 0x77 0x6F 0x72 0x6C 0x64 
uart1> 0x01 "A" "B" 0x2:2
WRITE: 0x01
WRITE: 0x41
WRITE: 0x42
WRITE: 0x02 0x02 
uart1> test
WRITE: 0x74 0x65 0x73 0x74 
>
```

Added freeform string input on command line

---

common/common.mk
common/ffconf.h
common/microsd.c
common/microsd.h
common/script.c
common/script.h
hydrabus/commands.c
hydrabus/commands.h
main.c

This PR adds a new *sd script* subcommand to execute commands stored in a text file on an SD card.
Rules are simple : 
- One command per line
- Any line beginning with a **#** will be ignored
It is also possible to create a file called *initscript* at the root of the sdcard that will be automatically executed everytime the console is initialized.

Scripting support

---

common/common.c
common/common.h
hydrabus/commands.c
hydrabus/hydrabus_mode_i2c.c
hydrabus/hydrabus_mode_spi.c
hydrabus/hydrabus_mode_threewire.c
hydrabus/hydrabus_mode_twowire.c
hydrabus/hydrabus_mode_uart.c

This PR adds the ´hd´ (HexDump) command in the following modes : 
- spi
- i2c
- uart
- 2- and 3-wire
For instance, this displays the first 32 bytes of an i2c EEPROM : 
```
i2c1> [ 0xa0 0x00 [ 0xa1 hd:32 ]
I2C START
WRITE: 0xA0 ACK 0x00 ACK 
I2C START
WRITE: 0xA1 ACK 
5B 30 78 61 31 FF FF FF  42 00 75 00 80 08 00 01  |  [0xa1...B.u..... 
0E FF 0C 01 02 20 00 A0  75 00 00 50 3C 50 2D 20  |  ..... ..u..P<P-  
NACK
I2C STOP
```

Hexdump in console

---

common/exec.c
hydrabus/commands.c
hydrabus/commands.h
hydrabus/hydrabus.mk
hydrabus/hydrabus_bbio.c
hydrabus/hydrabus_bbio.h
hydrabus/hydrabus_bbio_onewire.c
hydrabus/hydrabus_bbio_onewire.h
hydrabus/hydrabus_mode.c
hydrabus/hydrabus_mode_onewire.c
hydrabus/hydrabus_mode_onewire.h

Support for 1-wire protocol (https://www.maximintegrated.com/en/products/digital/one-wire.html)
- All the basic console commands supported
- `scan` command scans the 1-wire bus to locate devices
- BBIO 1-wire mode

Initial 1-wire support

---

hydrabus/hydrabus_mode_i2c.c
hydrabus/hydrabus_mode_onewire.c
hydrabus/hydrabus_mode_spi.c
hydrabus/hydrabus_mode_threewire.c
hydrabus/hydrabus_mode_twowire.c

Now the `hd` command can accept a 32-bit unsigned number.
Now up to 4294967295 bytes can be read at once

Change maximum size of hexdump command

---

hydrabus/hydrabus_sump.c
hydrabus/hydrabus_sump.h
main.c

This patch adds the possibility to automatically switch to SUMP mode
when Hydrabus is polled by a SUMP client (tested with OLS client and
Sigrok).

Add SUMP mode autodetection

---

hydrabus/hydrabus_mode.c
hydrabus/hydrabus_mode.h
hydrabus/hydrabus_mode_i2c.c
hydrabus/hydrabus_mode_onewire.c
hydrabus/hydrabus_mode_spi.c
hydrabus/hydrabus_mode_threewire.c
hydrabus/hydrabus_mode_twowire.c
hydrabus/hydrabus_mode_uart.c

This patch refactors the hexdump feature.
* `hd` command is handled in `cmd_mode_exec` and common in all modes
* The `dump` function in all modes is now a read with no console output
* New member of structure `mode_exec_t` maps the `dump` function

Hexdump feature refactor

---

drv/stm32cube/bsp_can.c
drv/stm32cube/bsp_can.h
hydrabus/commands.c
hydrabus/commands.h
hydrabus/hydrabus_bbio.h
hydrabus/hydrabus_bbio_can.c
hydrabus/hydrabus_mode_can.c
hydrabus/hydrabus_mode_can.h

This PR adds the LAWICEL/SLCAN protocol in the CAN mode. 
It allows to use the Linux `can-utils` tools to ease the CAN bus analysis

[WIP] Add SLCAN support for CAN mode

---

src/Makefile
src/common/microsd.c
src/drv/stm32cube/bsp_can.c
src/drv/stm32cube/bsp_i2c.c
src/drv/stm32cube/bsp_i2c.h
src/hydrabus/hydrabus_bbio_i2c.c
src/hydrabus/hydrabus_bbio_onewire.c
src/hydrabus/hydrabus_bbio_uart.c
src/hydrabus/hydrabus_mode.c
src/hydrabus/hydrabus_mode_can.c
src/hydrabus/hydrabus_mode_i2c.c
src/hydrabus/hydrabus_mode_uart.c

Since GCC 8.1 fixes the LTO bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69866), it is possible to use it for compiling HydraFW.
These patches correct some warnings/errors leveraged by GCC 8.1 and change the compilation options to produce RELEASE firmware by default.

GCC 8.1 fixes

---

src/main.c

Allow 2 consecutive entry in binary mode
This fixes a freeze when using flashrom (https://github.com/Baldanos/flashrom) it sends a reset command (which exits binary mode) right after it sends a new sequence of 20 0x00 to enter again binary mode. This result in a variable i equal to 40 but we never entry in binary mode again. 
This might also solve https://github.com/hydrabus/hydrafw/issues/76

Fix consecutive BBIO

---

contrib/pyHydra_93c46/README.md
contrib/pyHydra_93c46/hydra_93c46.py
contrib/pyHydrabus/pyHydrabus/auxpin.py
contrib/pyHydrabus/pyHydrabus/rawwire.py

16-bit mode supported only, 8-bit mode not supported yet.

Add contrib script for 93c46 EEPROM

---

src/hydrabus/hydrabus_mode.c

Small improvement on display of msec delays :
>spi1> %:4
DELAY: 4 ms
Unable to do the same with usec because the display of an output can cause a timing issue.

Display improvement for delays (msec)

---

contrib/pyHydrabus/pyHydrabus/hydrabus.py
contrib/pyHydrabus/pyHydrabus/protocol.py
contrib/pyHydrabus/pyHydrabus/uart.py

1. Add hydrabus @property in the Protocol class to access hydrabus class functions and serial methods from any protocol classes instances
2. Add in_waiting @property in the Hydrabus class
3. Add a timeout to Hydrabus class reset function, to avoid infinite loop
4. Set _baud value only if accepted by the hydrabus (0x01 returned)

Some improvements to pyHydrabus

---

src/hydranfc/trf7970a/src/trf797x.c

The TRF7970 FIFO size is 127 byte while it was limited to 38 bytes.  Now, we can directly send 122 bytes of data to a card, the other 5 bytes are configuration bytes used by the TRF7970.

Modify trf7970 fifo to its maximal value (127)

---

src/hydrabus/hydrabus_mode_spi.c
src/hydrabus/hydrabus_mode_spi.h
src/hydrabus/hydrabus_serprog.c

Tested with flashrom 1.2.
Flashrom debug output and time to read SPI flash seem to indicate that this is working correctly.
Thanks a lot for your great work on the HydraBus and this firmware.

Implement serprog protocol SPI speed for flashrom

---

contrib/SPI_flasher/HydraSPI.py
contrib/SPI_flasher/README.md
src/hydrabus/hydrabus_bbio_spi.c

- fix bug in `hydrabus_bbio_spi.c` (now `0b10000xyz` command works correctly)
- add SPI flasher script, see `README.md`

Hydra SPI Flasher

---

.gitignore
src/common/mode_config.h
src/drv/stm32cube/bsp_i2c_master.c
src/drv/stm32cube/bsp_i2c_master.h
src/hydrabus/commands.c
src/hydrabus/commands.h
src/hydrabus/hydrabus_mode_i2c.c

This change adds the ability of handling i2c clock stretching. Clock stretching could happen on certain devices, such as BNO055 and PN532. When it happens, we could not sending the I2C read/writes blindly, but have to wait until the SCL coming back to high before sending the next bits. Otherwise, the SDA signals will be ignored by the device and ends up with incorrect communication.
However, clock stretching can cause I2C bus hang indefinitely by faulty devices, so many devices doesn't do clock stretching at all. So due to the rareness of clock stretching, this feature is turned off by default. And we need to explicitly enable it with the following command when running in i2c mode:
```
clock-stretch <clock-tick-count>
```
If we specify 0, it will disable the feature, otherwise it means …

I2C: Add clock stretching support.

---

src/Makefile

Hello. Just decided to share this tiny improvement for the main `Makefile`: in the case of _compile-flash-run_ cycle, now just putting the device into _dfu mode_ & running `make flash` will do the rest automagically. Can't wait to hear any feedback about this patch.

src/Makefile: add target to flash firmware for convenience

---

src/Makefile

TL; DR: fix tab for `USE_VERBOSE_COMPILE=yes  make` use case.
Hello again. I have a couple of other ideas for further little improvements of `src/Makefile`, if no one minds. But during experiments, I discovered a very little issue which I'm happy to help to fix first.
Steps to reproduce:
- run a local build with verbose output using supported `make` variable:  
`$ USE_VERBOSE_COMPILE=yes  make`
What should happen? :
- successfull local build with detailed output
What actually happens? :
- build stops due to error:
`Makefile:327: *** missing separator.  Stop.`
Root cause:
- a set of spaces placed in the line with error instead of tab
Hence, this microscopic PR commit fixes verbose building.

src/Makefile: correcting tabulation to fix verbose build

---

src/Makefile

TL; DR: use a trick allowed by `GNU make` to avoid verbosity checks inside targets. Also, unify output according to logic of `rules.mk` from `ChibiOS`: if verbosity then print full command only, if silent then print message only; but not both nor neither.
---
I use projects with `make` for a few years myself but only recently I discovered this trick. Sometimes I use it myself when I need to switch on/off verbosity on the fly. I hope it will be useful here as well. But if it's too _hacky_ to accept, then I will understand.
Oh, and since there is `-f` flag for `rm`, then ignoring possible errors (such as `File doesn't exist`) through `-` prefix inside related call is not necessarily as far as I understand.
Test builds (with and without `USE_VERBOSE_COMPILE=yes`) have been done successfully …

src/Makefile: avoid verbosity checks inside targets

---

src/Makefile

TL; DR: make `make clean` clean _all_ produced files.
Steps to reproduce:
- run build: `$ make`
- clean produced files: `$ make clean`
What should happen:
- usually, it's a common practice when after `make clean` _all_ produced files are deleted
What actually happens:
- `src/common/hydrafw_version.hdr` kept as _"leftover"_
At first I was thinking about adding a separate `clean` target into `Makefile` but since internal variables of `rules.mk` from `ChibiOS` support "custom enhancements", just adding command `rm -f src/common/hydrafw_version.hdr` to special variable do the trick.
I did successfully test it myself on `Ubuntu 18.04`. But I did not test it on `Windows`/`mingw` unfortunately.
P.S. Happy New Year! :)

src/Makefile: make 'make clean' clean all produced files

---

src/hydrabus/commands.c

Hello. Just another tiny help - patch to close [the related task](https://github.com/hydrabus/hydrafw/issues/152).
The local build has been successfully tested. The log from my `hydrabus`:
```
> jtag
Device: JTAG1
GPIO resistor: pull-up
Frequency: 2000000Hz
Bit order: LSB first
jtag1> help brute
Bruteforce JTAG pins on x pins starting from PB0
bypass         Performs a BYPASS scan on x pins (PB0 up to PB11)
idcode         Performs an IDCODE scan on x pins (PB0 up to PB11)
jtag1> exit
> 2-wire
Device: twowire1
GPIO resistor: floating
Frequency: 1000000Hz
Bit order: MSB first
twowire1> help brute
Perform a SWD enumeration on x pins (PB0 up to PB11)
twowire1> exit
>
```
Is it ok? Or should the `2-wire` help output be in _**the full accordance**_ with …

src/hydrabus/commands.c: improve help output on some console commands

---

utils/udev-rules/09-hydrabus-arch_linux.rules

This PR fix a problem found in [TLP](https://wiki.archlinux.org/title/TLP) where by default all USB device are set to autosuspend, thus sometimes creating weird issue on the hydrabus.
It also create a symlink into /dev/hydrabusX where X is the number of hydrabus connected (with X starting at 1).

Arch Linux Fix autosuspend send by TLP daemon

---

src/Makefile

TL; DR: add support for `V=1` (in addition to `USE_VERBOSE_COMPILE=yes`).
Since this is a well-known common practice for open-source projects to enable verbose build just by adding `V=1` into build command, I thought this may be useful here as well - it's way much faster & easier to use.

src/Makefile: add V=1 parsing to enable verbose compile in easier classic way

---

src/common/microsd.c
src/drv/stm32cube/bsp.c
src/hydrabus/hydrabus_sd.c
src/main.c

Don't hardcode PCLK frequencies.
Remove unused #includes.
Enable USB2 console only when the peripheral exist.

Small cleanups.

---

src/drv/stm32cube/bsp_smartcard.c
src/hydrabus/hydrabus_bbio_smartcard.c
src/hydrabus/hydrabus_mode_smartcard.c

Hi,
Here's a patch adding a command to receive a smartcard message with a timeout. 
With the existing code, a successful read can only be achieved by specifying the exact number of characters (or less). This works: 
```
smartcard1> ]%%[read:18 
RST DOWN
DELAY: 1 ms
DELAY: 1 ms
RST UP
READ: 0x3B 0xF8 0x13 0x00 0x00 0x81 0x31 0xFE 0x45 0x4A 0x43 0x4F 0x50 0x76 0x32 0x34 0x31 0xB7 
```
But not this:
```
smartcard1> ]%%[read:33
RST DOWN
DELAY: 1 ms
DELAY: 1 ms
RST UP
READ error:3
```
Of course, ATR is just an example, we don't always know the size of the data returned by the card.. So I added a new `tread` (timed read) command and a `timeout` parameter. And now we can do this:
```
> smartcard 
Device: SMARTCARD1
Speed: 9408 bps
Parity: even
Stop bits: 1.5
Convention: normal
Prescaler: 12 / …
```

Add timed read for smartcards + littles changes

---

src/common/mode_config.h
src/drv/stm32cube/bsp_smartcard.c
src/drv/stm32cube/bsp_smartcard.h
src/drv/stm32cube/bsp_uart.c
src/drv/stm32cube/bsp_uart.h
src/hydrabus/commands.c
src/hydrabus/commands.h
src/hydrabus/hydrabus_bbio_smartcard.c
src/hydrabus/hydrabus_bbio_uart.c
src/hydrabus/hydrabus_mode.c
src/hydrabus/hydrabus_mode.h
src/hydrabus/hydrabus_mode_i2c.c
src/hydrabus/hydrabus_mode_jtag.c
src/hydrabus/hydrabus_mode_lin.c
src/hydrabus/hydrabus_mode_onewire.c
src/hydrabus/hydrabus_mode_smartcard.c
src/hydrabus/hydrabus_mode_spi.c
src/hydrabus/hydrabus_mode_threewire.c
src/hydrabus/hydrabus_mode_twowire.c
src/hydrabus/hydrabus_mode_uart.c
src/hydrabus/hydrabus_trigger.c

Based on #164 this PR adds a read with timeout feature.
1) Add a `timeout` keyword to set timeout in miliseconds on all relevant modes (UART, LIN, Smartcard)
2) Change `read` and `hd` commands behavior. They now display read bytes and show an message if not every byte requested could be read
3) Some cleanup of now unused functions
Example with UART in loopback mode:
```
> uart 
Device: UART1
Speed: 9600 bps
Parity: none
Stop bits: 1
Timeout: 10000 msec
uart1> timeout 1000
uart1> show 
Device: UART1
Speed: 9600 bps
Parity: none
Stop bits: 1
Timeout: 1000 msec
uart1> 0x41 r:8
WRITE: 0x41
! TIMEOUT: read 1 out of 8
READ: 0x41
uart1> 0x41 hd:8
WRITE: 0x41
41                                                |  A 
! TIMEOUT: read 1 out of 8
uart1>
```
This might need to be further tested before …

Add read with timeout feature

---

.github/workflows/push.yml
scripts/env.sh
src/build-scripts/hydrafw-revision.py
src/build-scripts/hydrafw-version.py

TL;DR: utilize GitHub capabilities to make builds on every commit and on every pull-request.
Hello. I'm a bit surprised that this haven't been done yet. So I decided to take some liberty to help with that. There may be a lot of room for improvements in the future but this is _work-able_ proof-of-concept which can be merged & adopted as is currently in my humble opinion. However, to fully integrate `push.yml` into `hydrafw` github project, admins may need to set some additional settings _somewhere_ in _Settings_ of the project using GitHub web interface manually.
The benefits are:
- always be sure that current code at least _build-able_;
- without need to enroll local devel environment, advanced users who just will need `dfu-util`, always be able to get the latest fresh build from main …

CI/CD basic implementation based on GitHub Actions

---

.github/workflows/push.yml
scripts/env.sh

Set additional variable in `push.yml` to explicitly indicate building on _GitHub_ regardless a kind/trigger for a build (PR, merge, etc.).
:crossed_fingers: _Hopefully_ it should fix #168 , but I'm afraid we won't be able to find this out for 100% without merging this fix first.
P.S. Please, take my apologies for this bloop.

push.yml/env.sh: set helper variable to indicate building on github explicitly

---

scripts/env.sh

This commit resolves the error encountered when GITHUB_CI_CD is unset or non-integer by defaulting it to 0.
```
./scripts/env.sh: line 22: [: : integer expression expected
```

Fix integer comparison error by ensuring GITHUB_CI_CD is defined
